/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        Stack<Integer> stack = new Stack<>();
        stack.push(5);
        stack.push(6);
        stack.push(7);
        stack.push(9);
        stack.pop();
        stack.pop();
        stack.pop();
        stack.pop();
        System.out.println(stack.isEmpty());

        Queue<Integer> queue = new Queue<>();


        queue.enqueue(15);
        queue.enqueue(16);
        queue.enqueue(17);
        queue.enqueue(18);
        queue.dequeue();
        queue.dequeue();
        queue.dequeue();
        queue.dequeue();
        System.out.println(queue);

        PseudoQueue<Integer> pseudoQueue = new PseudoQueue<>();
        pseudoQueue.enqueue(15);
        pseudoQueue.enqueue(16);
        pseudoQueue.enqueue(17);
        pseudoQueue.enqueue(18);
        pseudoQueue.dequeue();
        pseudoQueue.dequeue();
        pseudoQueue.dequeue();
        pseudoQueue.dequeue();
        System.out.println(pseudoQueue.toString());

        AnimalShelter shelter = new AnimalShelter();
        shelter.enqueue(new Animal("cat"));
        shelter.enqueue(new Animal("dog"));
        shelter.enqueue(new Animal("cat"));
        shelter.enqueue(new Animal("dog"));

        System.out.println(shelter.getCats().getIdx());
    }
}
